Pistahouse/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'ph/index'

  get 'ph/show'

  get 'ph/delete'

  get 'ph/edit'

  get 'ph/order'

  get 'ph/home'

  get 'pistahouseinfo/home'

  get 'pistahouseinfo/menu'

  get 'pistahouseinfo/place'

  get 'pistahouseinfo/contactus'

  get 'pistahouseinfo/show'

  get 'pistahouseinfo/edit'

  get 'pistahouseinfo/delete'

  get 'pistahouseinfo/new'

  match ':controller(/:action(/:id))', :via=>[:get, :post]
  
  root 'pistahouseinfo#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Pistahouse/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Pistahouse/app/models/fooditem.rb
class Fooditem < ActiveRecord::Base
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

Pistahouse/app/models/place.rb
class Place < ApplicationRecord
end

Pistahouse/app/models/section.rb
class Section < ActiveRecord::Base
	def self.all
		%w{breakfast lunch dinner drinks}
	end
end

Pistahouse/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

Pistahouse/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
before_action :authenticate_user!
end

Pistahouse/app/controllers/ph_controller.rb
class PhController < ApplicationController
   def index
    @o=Place.all(params[:page]).per(10)
  end

  def home
    @o=Place.all
  end

  def create
    @o=Place.new(ord_params)
    if @o.save
      redirect_to(:action=>'home')
    else
      render('index')
    end
  end
  def new
    @o=Place.new
  end

  def show
    @o=Place.find(params[:id])
    @fooditem=Fooditem.find(params[:id])
  end

  def delete
    @ord=Place.find(params[:id])
  end

  def destroy
    @ord=Place.find(params[:id])
    if @ord.destroy
      redirect_to(:action=>'home')
    else
      render('delete')
    end
  end

  def edit
  end

  def order
  end

  private
  def ord_params
    params.require(:ord).permit(:name, :phonenum, :address)
  end

end

Pistahouse/app/controllers/pistahouseinfo_controller.rb
class PistahouseinfoController < ApplicationController
   def index
    
    end

  def menu
    if
    params[:section]
    @fooditem=Fooditem.where Section: params[:section]
	 else
    @fooditem=Fooditem.all
  end
end

  def contactus
  end

  def show
    @fooditem=Fooditem.find(params[:id])
  end

  def edit
    @food=Fooditem.find(params[:id])
  end

  def update
    @food=Fooditem.find(params[:id])
    if @food.update_attributes(food_params)
      redirect_to(:action=>'menu')
    else
      render('edit')
    end
  end

  def delete
  end

  def new
    @fooditem=Fooditem.new
  end

  def create
    @fooditem=Fooditem.new(food_params)
    if @f.save
      redirect_to(:action=>'home')
    else
      render('new')
    end
  end

  private
  def food_params
    params.require(:food).permit(:name, :price, :description, :section, :image)
  end
end

Pistahouse/app/helpers/application_helper.rb
module ApplicationHelper
end

Pistahouse/app/helpers/ph_helper.rb
module PhHelper
end

Pistahouse/app/helpers/pistahouseinfo_helper.rb
module PistahouseinfoHelper
end

Pistahouse/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pistahouse</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

    <%= yield %>
  </body>
</html>

Pistahouse/app/views/ph/create.html.erb
<h1>Ph#create</h1>
<p>Find me in app/views/ph/create.html.erb</p>

Pistahouse/app/views/ph/delete.html.erb
<%= form_for(:ord, url:{:action=>'destroy', :id=>@ord.id}) do |f|%>
<h1> Are you sure you want to delete the order </h1>
<div class="actions">
    <%= f.submit %>
  </div>
  <%end%>

Pistahouse/app/views/ph/destroy.html.erb
<h1>Ph#destroy</h1>
<p>Find me in app/views/ph/destroy.html.erb</p>

Pistahouse/app/views/ph/home.html.erb
<h1> Thanks for Placing the order <h1>

<% @o.each do |o|%>
	ID: <%= o.id%>
	<%= link_to "Your Order", {:action=>'show', :id=>o.id}, class:"btn btn-primary btn-lg"%>
	<%= link_to "delete", {:action=>'delete', :id=>o.id}, class:"btn btn-primary btn-lg"%>
	<%end%>

Pistahouse/app/views/ph/index.html.erb
<%= form_for(:ord, url:{:action=>'create'}) do |f|%>
<div class="field">
    <%= f.label :Name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :PhoneNumber %><br>
    <%= f.text_area :phonenum %>
  </div>
  <div class="form-group">
    <%= f.label :Address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Pistahouse/app/views/ph/new.html.erb
<h1>Thanks for placing the order</h1><br>
<%= o.id %>
	Name: <%= o.name %><br>
	PhoneNumber: <%= o.phonenum%><br>
	Address: <%= o.address%><br>
	<%= link_to "Delete", {:action=>'delete', :id=>o.id}, class:"btn btn-primary btn-lg"%><br>
	<%end%>

Pistahouse/app/views/ph/show.html.erb
    Name: <%= @o.name %><br>
	PhoneNumber: <%= @o.phonenum%><br>
	Address: <%= @o.address%><br>
    Item:  <%= @fooditem.name%><br>
    Price:  <%= @fooditem.price%><br>
    Delivery charges : 200<br>
    Description  <%= @fooditem.description%><br>
    Image:  <%=image_tag @fooditem.image.url%><br>

Pistahouse/app/views/pistahouseinfo/contactus.html.erb
Plot No.8,9,14,15<br>
Survey No.221, Beside Vijetha and Heritage supermarkets,<br> 
Madinaguda, Miyapur, Nandini Nagar<br>
Ambedkar Nagar, Hafeezpet<br>
Hyderabad, Telangana-500049<br>
Phone : 040 3399 4444

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d30442.07429737488!2d78.32180582515053!3d17.495131832891218!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bcb926be133aeff%3A0xc662327eb78876f3!2sKFC!5e0!3m2!1sen!2sin!4v1534429083722" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>

Pistahouse/app/views/pistahouseinfo/edit.html.erb
<%= form_for(:food, url:{:action=>'update', :id=>@food.id}) do |f|%>
<div class="field">
    <%= f.label :Name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_area :price %>
  </div>
  <div class="field">
    <%= f.label :Description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :section %><br>
    <%= f.text_area :section%>
  </div>
  <div class="form-group">
    <%= f.label :photo %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Pistahouse/app/views/pistahouseinfo/index.html.erb
<div class="card text-center">
  <div class="card-header">
  </div>
  <div class="card-body">
    <h1 class="card-title">Welcome to grand PISTA HOUSE</h1>
    <p class="card-text">PISTA HOUSE, also known as Kentucky Fried Chicken, is an American fast food restaurant chain that specializes in fried chicken.</p>
    <a <%= link_to "MENU", pistahouseinfo_menu_path, class:"btn btn-primary btn-lg"%></a>
    <a <%= link_to "Contact US", pistahouseinfo_contactus_path, class:"btn btn-primary btn-lg" %></a>
  </div>

Pistahouse/app/views/pistahouseinfo/menu.html.erb
  <div class="card-footer text-muted">
    
  </div>
</div>
<% Section.all.each do |section| %>
<%= link_to section, pistahouseinfo_menu_path(section: section), class:"btn btn-primary btn-lg"%>
<%end%>

<table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Name</th>
      <th scope="col">Price</th>
      <th scope="col">Description</th>
      <th scope="col">Image</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    <% @fooditem.each do |i|%>
      <td><%= i.id %></td>
      <td><%= i.name%></td>
      <td><%= i.price%></td>
      <td><%= i.description%></td>
      <td><%=image_tag i.image.url(:thumb)%></td>

      <td><%= link_to "show", {:action=>'show', :id=>i.id}, class:"btn btn-primary btn-lg"%></td>
      <td><%= link_to "Edit", {:action=>'edit', :id=>i.id}, class:"btn btn-primary btn-lg"%></td>
      <td><%= link_to "Place order", {:action=>'place', :id=>i.id}, class:"btn btn-primary btn-lg"%></td>
    </tr>
    <%end%>
    
  </tbody>
</table>

Pistahouse/app/views/pistahouseinfo/new.html.erb
<h1>Fooditeaminfo#new</h1>
<%= form_for(:food, url:{:action=>'create'}) do |f|%>
<div class="field">
    <%= f.label :Name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_area :price %>
  </div>
  <div class="field">
    <%= f.label :Description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :section %><br>
    <%= f.text_area :section%>
  </div>
  <div class="form-group">
    <%= f.label :photo %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Pistahouse/app/views/pistahouseinfo/place.html.erb
<h1> Are you sure you want to place the order </h1>
<%= link_to "Yes", ph_index_path, class:"btn btn-primary btn-lg"%>
<%= link_to "No", pistahouseinfo_menu_path, class:"btn btn-primary btn-lg"%>

Pistahouse/app/views/pistahouseinfo/show.html.erb
<div class="p-3 mb-2 bg-secondary text-white">
<%=image_tag @fooditem.image.url%><br>
</div>